name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v5.0.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./resources
        server-dir: /mods/deathmatch/resources
        dangerous-clean-slate: true
